//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mastermind.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mastermind.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Abandonnees.
        /// </summary>
        public static string abandoned {
            get {
                return ResourceManager.GetString("abandoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parties abandonnées.
        /// </summary>
        public static string abandonedGames {
            get {
                return ResourceManager.GetString("abandonedGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accès refusé, veuillez vous connecter avec un autre utilisateur..
        /// </summary>
        public static string AccessDeniedChangeUserMsg {
            get {
                return ResourceManager.GetString("AccessDeniedChangeUserMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accès refusé, veuillez vous connecter avec un autre utilisateur..
        /// </summary>
        public static string AccessDeniedChangeUserMsg1 {
            get {
                return ResourceManager.GetString("AccessDeniedChangeUserMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accès refusé, veuillez vous connecter..
        /// </summary>
        public static string AccessDeniedMsg {
            get {
                return ResourceManager.GetString("AccessDeniedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administration.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Êtes-vous certain de vouloir supprimer cet item ?.
        /// </summary>
        public static string AreYouSureDeleteItem {
            get {
                return ResourceManager.GetString("AreYouSureDeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tentatives.
        /// </summary>
        public static string attemps {
            get {
                return ResourceManager.GetString("attemps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Moyenne de coups.
        /// </summary>
        public static string averageStrokes {
            get {
                return ResourceManager.GetString("averageStrokes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour à la page d&apos;acceuil.
        /// </summary>
        public static string BackToHomepage {
            get {
                return ResourceManager.GetString("BackToHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour à la page de connexion.
        /// </summary>
        public static string BackToLoginPage {
            get {
                return ResourceManager.GetString("BackToLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour vers la liste des membres.
        /// </summary>
        public static string BackToMemberList {
            get {
                return ResourceManager.GetString("BackToMemberList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commencer une partie de Mastermind.
        /// </summary>
        public static string begin {
            get {
                return ResourceManager.GetString("begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour commencer, il vous suffit de sélectionner &quot;Jouer une partie&quot; en cliquant sur le bouton ci-bas ou via le menu principal.  Vous pourrez alors commencer à faire des propositions de combinaisons.  Pour cela, vous devez simplement positionner {0} pions dans la première ligne située complètement en bas.  Vous devez d&apos;abord sélectionner la couleur, puis cibler la position sur la ligne active de couleur bleue..
        /// </summary>
        public static string beginText {
            get {
                return ResourceManager.GetString("beginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Couleurs.
        /// </summary>
        public static string colors {
            get {
                return ResourceManager.GetString("colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configurations.
        /// </summary>
        public static string config {
            get {
                return ResourceManager.GetString("config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmer vos choix.
        /// </summary>
        public static string confirmChoices {
            get {
                return ResourceManager.GetString("confirmChoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creer un nouveau compte.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Crée un profil.
        /// </summary>
        public static string CreateProfil {
            get {
                return ResourceManager.GetString("CreateProfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configurations actuelles.
        /// </summary>
        public static string currentConfig {
            get {
                return ResourceManager.GetString("currentConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tableau de bord.
        /// </summary>
        public static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer un membre.
        /// </summary>
        public static string DeleteMember {
            get {
                return ResourceManager.GetString("DeleteMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier votre compte.
        /// </summary>
        public static string EditAccount {
            get {
                return ResourceManager.GetString("EditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier un membre.
        /// </summary>
        public static string EditMember {
            get {
                return ResourceManager.GetString("EditMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Courriel.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Moins de coups.
        /// </summary>
        public static string fewerHits {
            get {
                return ResourceManager.GetString("fewerHits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom complet.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Partie en cours.
        /// </summary>
        public static string gameProgress {
            get {
                return ResourceManager.GetString("gameProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parties perdues.
        /// </summary>
        public static string gamesLost {
            get {
                return ResourceManager.GetString("gamesLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parties gagnées.
        /// </summary>
        public static string gamesWon {
            get {
                return ResourceManager.GetString("gamesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configurations globales.
        /// </summary>
        public static string globalSettings {
            get {
                return ResourceManager.GetString("globalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le but de  Mastermind.
        /// </summary>
        public static string goal {
            get {
                return ResourceManager.GetString("goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le but du Mastermind est de trouver la combinaison secrète composée de {0} couleurs dans un maximum de {1} coups. Cette combinaison secrète est générée automatiquement lors d&apos;une nouvelle   Prendre note qu&apos;une même couleur peut se répéter dans la combinaison cachée..
        /// </summary>
        public static string goalText {
            get {
                return ResourceManager.GetString("goalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identification.
        /// </summary>
        public static string Identification {
            get {
                return ResourceManager.GetString("Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Cet id de membre n&apos;existe pas .
        /// </summary>
        public static string Idwrong {
            get {
                return ResourceManager.GetString("Idwrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chemin de l&apos;image.
        /// </summary>
        public static string ImagePath {
            get {
                return ResourceManager.GetString("ImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format de courriel invalide.
        /// </summary>
        public static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom d&apos;utilisateur ou mot de passe invalide !.
        /// </summary>
        public static string InvalidUsernamePassword {
            get {
                return ResourceManager.GetString("InvalidUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette {0} est introuvable..
        /// </summary>
        public static string ItemNotFoundControllerMsgM {
            get {
                return ResourceManager.GetString("ItemNotFoundControllerMsgM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à fr.
        /// </summary>
        public static string LangISOCode {
            get {
                return ResourceManager.GetString("LangISOCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Perdues.
        /// </summary>
        public static string lost {
            get {
                return ResourceManager.GetString("lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez perdu.
        /// </summary>
        public static string lostMessage {
            get {
                return ResourceManager.GetString("lostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mastermind.
        /// </summary>
        public static string Mastermind {
            get {
                return ResourceManager.GetString("Mastermind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Membre.
        /// </summary>
        public static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des membres.
        /// </summary>
        public static string MemberList {
            get {
                return ResourceManager.GetString("MemberList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Membres.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La longueur doit être entre {2} et {1}.
        /// </summary>
        public static string ModelLengthBetween {
            get {
                return ResourceManager.GetString("ModelLengthBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La longueur doit être plus petite que {1}.
        /// </summary>
        public static string ModelLengthLessThan {
            get {
                return ResourceManager.GetString("ModelLengthLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez choisir entre {1} et {2} tentatives..
        /// </summary>
        public static string modelNumberAttemptsBetween {
            get {
                return ResourceManager.GetString("modelNumberAttemptsBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez choisir entre {1} et {2} couleurs..
        /// </summary>
        public static string modelNumberColorsBetween {
            get {
                return ResourceManager.GetString("modelNumberColorsBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez choisir entre {1} et {2} positions..
        /// </summary>
        public static string modelNumberPositionsBetween {
            get {
                return ResourceManager.GetString("modelNumberPositionsBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} obligatoire.
        /// </summary>
        public static string ModelRequired {
            get {
                return ResourceManager.GetString("ModelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier votre profil.
        /// </summary>
        public static string ModifyProfil {
            get {
                return ResourceManager.GetString("ModifyProfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelle partie.
        /// </summary>
        public static string newGame {
            get {
                return ResourceManager.GetString("newGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun item trouvé..
        /// </summary>
        public static string NoItemFound {
            get {
                return ResourceManager.GetString("NoItemFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de tentatives.
        /// </summary>
        public static string numberAttempts {
            get {
                return ResourceManager.GetString("numberAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de couleurs.
        /// </summary>
        public static string numberColors {
            get {
                return ResourceManager.GetString("numberColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de positions.
        /// </summary>
        public static string numberPositions {
            get {
                return ResourceManager.GetString("numberPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jouer une partie.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Positions.
        /// </summary>
        public static string positions {
            get {
                return ResourceManager.GetString("positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une fois votre compte créé/modifié, vous serez directement redirigés vers la page d&apos;authentification pour vous &quot;loguer&quot;.
        /// </summary>
        public static string RedirectToLogin {
            get {
                return ResourceManager.GetString("RedirectToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rejouer.
        /// </summary>
        public static string replay {
            get {
                return ResourceManager.GetString("replay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Si la combinaison est correcte.
        /// </summary>
        public static string rightCombinaison {
            get {
                return ResourceManager.GetString("rightCombinaison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez réussi le défi et la combinaison secrète sera révélée. Un des sous objectifs est de réussir en le moins de coups possibles..
        /// </summary>
        public static string rightCombinaisonText {
            get {
                return ResourceManager.GetString("rightCombinaisonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Règlements.
        /// </summary>
        public static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Règlements inspirés de .
        /// </summary>
        public static string rulesInspired {
            get {
                return ResourceManager.GetString("rulesInspired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisissez vos couleurs.
        /// </summary>
        public static string selectColors {
            get {
                return ResourceManager.GetString("selectColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Se connecter.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Se déconnecter.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vos statistiques.
        /// </summary>
        public static string statistics {
            get {
                return ResourceManager.GetString("statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sommaire de toutes les parties.
        /// </summary>
        public static string summary {
            get {
                return ResourceManager.GetString("summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Astuces pour déchiffrer la combinaison secrète du Mastermind.
        /// </summary>
        public static string tips {
            get {
                return ResourceManager.GetString("tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Si vous approchez de la fin de partie et que vous n’avez toujours pas déchiffrer la combinaison secrète, il est judicieux de comparer les lignes sur lesquels vous avez fait les meilleurs scores. Les lignes ayant zéro couleur trouvée peuvent également être utile pour éliminer définitivement des couleurs..
        /// </summary>
        public static string tipsText {
            get {
                return ResourceManager.GetString("tipsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom d&apos;utilisateur.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom d&apos;utilisateur existe déjà.
        /// </summary>
        public static string UsernameAlreadyExists {
            get {
                return ResourceManager.GetString("UsernameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Site web.
        /// </summary>
        public static string website {
            get {
                return ResourceManager.GetString("website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bienvenue.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gagnees.
        /// </summary>
        public static string won {
            get {
                return ResourceManager.GetString("won", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez gagné.
        /// </summary>
        public static string wonMessage {
            get {
                return ResourceManager.GetString("wonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Si la combinaison présentée est incorrecte.
        /// </summary>
        public static string wrongCombination {
            get {
                return ResourceManager.GetString("wrongCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Si dans la proposition, un ou plusieurs pions de couleurs sont bien dans la combinaison mais pas à la bonne place, des marqueurs blancs seront positionnés selon le nombre dans la partie de droite de la ligne.  Si dans la proposition, un ou plusieurs pions de couleurs sont bien dans la combinaison et à la bonne place, ce sont des marqueurs noirs qui seront utilisés. Prendre note que la position des marqueurs n&apos;est pas liée à la position de la proposition.  Les marqueurs noirs sont d&apos;abord affichés, ensuite l [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string wrongCombinationText_0 {
            get {
                return ResourceManager.GetString("wrongCombinationText_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous continuez ainsi en proposant sur la seconde ligne une autre proposition, en prenant bien entendu en compte les marqueurs noirs et blancs. Vous avez droit à {0} propositions pour déchiffrer le code, sinon vous serez déclaré perdant et la combinaison secrète sera révélée. Vous pourrez ainsi analyser votre partie si vous le désirez. .
        /// </summary>
        public static string wrongCombinationText_1 {
            get {
                return ResourceManager.GetString("wrongCombinationText_1", resourceCulture);
            }
        }
    }
}
